version: "3.8"
services:
  php:
    container_name: "php"
    working_dir: "/app"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/app
      - ~/.composer/cache:/composer/cache
      - ./docker/php/conf.d/xdebug.ini:/usr/etc/php/conf.d/docker-php-ext-xdebug.ini
      - ./docker/php/conf.d/error_reporting.ini:/usr/etc/php/conf.d/error_reporting.ini
  nginx:
    container_name: "nginx"
    working_dir: "/app/public"
    image: nginx:stable-perl
    ports:
      - '80:80'
    volumes:
      - ./public:/app/public
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  postgres:
    container_name: "postgres"
    working_dir: "/app"
    image: "postgres:12.20-bullseye"
    environment:
      POSTGRES_USER: gianni
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: blog
    ports:
      - '5432:5432'
    volumes:
      - postgres:/var/lib/postgresql/data:delegated

volumes:
  postgres:
    name: postgres